on: [push]
env:
  resource_id: /subscriptions/6560575d-fa06-4e7d-95fb-f962e74efd7a/resourceGroups/saferollout/providers/Microsoft.MachineLearningServices/workspaces/saferollout/onlineEndpoints/gpt-2/deployments/blue
  cli_version: 2.0.0a1
  ws: saferollout
  rg: saferollout
  subs: 6560575d-fa06-4e7d-95fb-f962e74efd7a
jobs:
  test:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.7
      - run: |
          az extension add --source https://azuremlsdktestpypi.blob.core.windows.net/wheels/sdk-cli-v2-public/ml-${{ env.cli-version }}-py3-none-any.whl --pip-extra-index-urls https://azuremlsdktestpypi.azureedge.net/sdk-cli-v2-public -y
          az extension add --n log-analytics --yes

      - name: azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_TOKEN}}
      - name: Set defaults
        run: |
            az config set defaults.workspace=${{ env.ws }}
            az config set defaults.group=${{ env.rg }}
            az account set -s ${{ env.subs }}    
      - name: test-memory-within-threshold
        uses: actions/validate-metrics@v1
        with:
          chart_name: "Validate memory utilization within threshold"
          chart_save_path: chart-output
          metric: MemoryUtilization
          aggregation: Average
          metrics_condition: lte
          interval: PT1M
          num_intervals: 4         
          threshold: 30
          resource_id: ${{ env.resource_id }}
